language: objective-c
xcode_project: SpatialConnect.xcodeproj
xcode_scheme: SpatialConnect

osx_image: xcode7.3
notifications:
  email:
    - spatialconnect@boundlessgeo.com

script:
  xctool
  -project SpatialConnect.xcodeproj
  -scheme SpatialConnect
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew uninstall --force xctool && travis_wait 30 brew install --HEAD xctool

before_script:
  - carthage bootstrap

before_deploy:
  - carthage build --no-skip-current
  - carthage archive SpatialConnect
