language: objective-c
xcode_project: SpatialConnect.xcodeproj
xcode_scheme: SpatialConnect

osx_image: xcode7.1
notifications:
  email: 
    - spatialconnect@boundlessgeo.com

install: travis_wait 60 pod install

script:
  xctool
  -workspace SpatialConnect.xcworkspace
  -scheme SpatialConnect
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew uninstall xctool && travis_wait 30 brew install --HEAD xctool
